/**
 * Payload Local API
 * The Payload Local API available in your running payloads. It provides an interface between your game server and the IMS zeuz orchestration service.  # Warning The Payload Local API is starting up at the same time as your game server, and may not be initially available. Use a retry mechanism to ensure the request is successful.  # OpenAPI Best practices The Payload local API is using the OpenAPI standard, it is advised to use an OpenAPI client generator for the language your game server uses. See a [list of OpenAPI client generators](https://openapi-generator.tech/docs/generators/).  # Address The Payload Local API address can be obtained using an environment variable: `http://${ORCHESTRATION_PAYLOAD_API}`.  # Authentication As the Payload Local API is only accessible from within the payload, it does not require authentication. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIProtocolV0.h"

#include "IMSZeuzAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace IMSZeuzAPI
{

inline FString ToString(const OpenAPIProtocolV0::Values& Value)
{
	switch (Value)
	{
	case OpenAPIProtocolV0::Values::Udp:
		return TEXT("UDP");
	case OpenAPIProtocolV0::Values::Tcp:
		return TEXT("TCP");
	case OpenAPIProtocolV0::Values::Tcpudp:
		return TEXT("TCPUDP");
	}

	UE_LOG(LogIMSZeuzAPI, Error, TEXT("Invalid OpenAPIProtocolV0::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPIProtocolV0::EnumToString(const OpenAPIProtocolV0::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPIProtocolV0::Values& Value)
{
	static TMap<FString, OpenAPIProtocolV0::Values> StringToEnum = { 
		{ TEXT("UDP"), OpenAPIProtocolV0::Values::Udp },
		{ TEXT("TCP"), OpenAPIProtocolV0::Values::Tcp },
		{ TEXT("TCPUDP"), OpenAPIProtocolV0::Values::Tcpudp }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPIProtocolV0::EnumFromString(const FString& EnumAsString, OpenAPIProtocolV0::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline FStringFormatArg ToStringFormatArg(const OpenAPIProtocolV0::Values& Value)
{
	return FStringFormatArg(ToString(Value));
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPIProtocolV0::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPIProtocolV0::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPIProtocolV0::WriteJson(JsonWriter& Writer) const
{
	WriteJsonValue(Writer, Value);
}

bool OpenAPIProtocolV0::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Value);
}

}
