/**
 * IMS Session Manager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace IMSSessionManagerAPI
{

/*
 * OpenAPIProtobufAny
 *
 * 
 */
class IMSSESSIONMANAGERAPI_API OpenAPIProtobufAny : public Model
{
public:
    virtual ~OpenAPIProtobufAny() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<FString> TypeUrl;
	TOptional<TArray<uint8>> Value;
};

}
