/**
 * IMS Session Manager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIV0Session.h"

namespace IMSSessionManagerAPI
{

/*
 * OpenAPIV0ListSessionsResponse
 *
 * ListSessionsResponse provides a list of sessions which includes each session&#39;s &#x60;session_status&#x60;.
 */
class IMSSESSIONMANAGERAPI_API OpenAPIV0ListSessionsResponse : public Model
{
public:
    virtual ~OpenAPIV0ListSessionsResponse() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* sessions holds list of game servers from matching proj id. */
	TArray<OpenAPIV0Session> Sessions;
};

}
