/**
 * IMS Session Manager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIV0Port.h"

namespace IMSSessionManagerAPI
{

/*
 * OpenAPIV0Session
 *
 * Session holds the game server data required for client to connect.
 */
class IMSSESSIONMANAGERAPI_API OpenAPIV0Session : public Model
{
public:
    virtual ~OpenAPIV0Session() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* id is the payload id. */
	FString Id;
	/* address is the payload ip. */
	FString Address;
	/* ports holds the port info for payload where player can connect to. */
	TArray<OpenAPIV0Port> Ports;
	/* session_status holds the key value pairs stored in the session_status annotation on the game server. */
	TMap<FString, FString> SessionStatus;
};

}
