/**
 * IMS Session Manager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace IMSSessionManagerAPI
{

/*
 * OpenAPIV0Port
 *
 * Port holds game server port info required to make the connection.
 */
class IMSSESSIONMANAGERAPI_API OpenAPIV0Port : public Model
{
public:
    virtual ~OpenAPIV0Port() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* name of the port. */
	FString Name;
	/* port The container's internal port number. */
	int32 Port = 0;
};

}
