/**
 * IMS Session Manager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIProtobufAny.h"

namespace IMSSessionManagerAPI
{

/*
 * OpenAPIRpcStatus
 *
 * 
 */
class IMSSESSIONMANAGERAPI_API OpenAPIRpcStatus : public Model
{
public:
    virtual ~OpenAPIRpcStatus() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<int32> Code;
	TOptional<FString> Message;
	TOptional<TArray<OpenAPIProtobufAny>> Details;
};

}
