/**
 * IMS Session Manager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "CoreMinimal.h"
#include "OpenAPIBaseModel.h"

namespace IMSSessionManagerAPI
{

class IMSSESSIONMANAGERAPI_API OpenAPISessionManagerV0Api
{
public:
	OpenAPISessionManagerV0Api();
	~OpenAPISessionManagerV0Api();

	/* Sets the URL Endpoint.
	* Note: several fallback endpoints can be configured in request retry policies, see Request::SetShouldRetry */
	void SetURL(const FString& Url);

	/* Adds global header params to all requests */
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	/* Sets the retry manager to the user-defined retry manager. User must manage the lifetime of the retry manager.
	* If no retry manager is specified and a request needs retries, a default retry manager will be used.
	* See also: Request::SetShouldRetry */
	void SetHttpRetryManager(FHttpRetrySystem::FManager& RetryManager);
	FHttpRetrySystem::FManager& GetHttpRetryManager();

	class CreateSessionV0Request;
	class CreateSessionV0Response;
	class ListSessionsV0Request;
	class ListSessionsV0Response;
	
    DECLARE_DELEGATE_OneParam(FCreateSessionV0Delegate, const CreateSessionV0Response&);
    DECLARE_DELEGATE_OneParam(FListSessionsV0Delegate, const ListSessionsV0Response&);
    
    FHttpRequestPtr CreateSessionV0(const CreateSessionV0Request& Request, const FCreateSessionV0Delegate& Delegate = FCreateSessionV0Delegate()) const;
    FHttpRequestPtr ListSessionsV0(const ListSessionsV0Request& Request, const FListSessionsV0Delegate& Delegate = FListSessionsV0Delegate()) const;
    
private:
    void OnCreateSessionV0Response(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FCreateSessionV0Delegate Delegate) const;
    void OnListSessionsV0Response(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FListSessionsV0Delegate Delegate) const;
    
	FHttpRequestRef CreateHttpRequest(const Request& Request) const;
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
	mutable FHttpRetrySystem::FManager* RetryManager = nullptr;
	mutable TUniquePtr<HttpRetryManager> DefaultRetryManager;
};

}
