/**
 * IMS Session Manager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIV0Port.h"

namespace IMSSessionManagerAPI
{

/*
 * OpenAPIV0CreateSessionResponse
 *
 * CreateSessionResponse from a game session creation request.
 */
class IMSSESSIONMANAGERAPI_API OpenAPIV0CreateSessionResponse : public Model
{
public:
    virtual ~OpenAPIV0CreateSessionResponse() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* id of the reserved game server. */
	TOptional<FString> Id;
	/* address IP address of the session. */
	TOptional<FString> Address;
	/* ports List of the ports for the session. */
	TOptional<TArray<OpenAPIV0Port>> Ports;
};

}
