/**
 * IMS Session Manager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace IMSSessionManagerAPI
{

/*
 * OpenAPIV0CreateSessionRequestBody
 *
 * 
 */
class IMSSESSIONMANAGERAPI_API OpenAPIV0CreateSessionRequestBody : public Model
{
public:
    virtual ~OpenAPIV0CreateSessionRequestBody() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* session_config to set on the game server. */
	TOptional<FString> SessionConfig;
};

}
