/**
 * IMS Session Manager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace IMSSessionManagerAPI
{

/*
 * OpenAPIV0ErrorResponse
 *
 * 
 */
class IMSSESSIONMANAGERAPI_API OpenAPIV0ErrorResponse : public Model
{
public:
    virtual ~OpenAPIV0ErrorResponse() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Error details. */
	TOptional<FString> Message;
	/* Unique request identifier. Quote the request ID if you raise a support ticket. */
	TOptional<FString> RequestId;
};

}
