/**
 * IMS Session Manager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "IMSSessionManagerAPIModule.h"

IMPLEMENT_MODULE(IMSSessionManagerAPIModule, IMSSessionManagerAPI);
DEFINE_LOG_CATEGORY(LogIMSSessionManagerAPI);

void IMSSessionManagerAPIModule::StartupModule()
{
}

void IMSSessionManagerAPIModule::ShutdownModule()
{
}
