/**
 * IMS Session Manager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPISessionManagerV0ApiOperations.h"

#include "IMSSessionManagerAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Dom/JsonObject.h"
#include "Templates/SharedPointer.h"
#include "HttpModule.h"
#include "PlatformHttp.h"

namespace IMSSessionManagerAPI
{

FString OpenAPISessionManagerV0Api::CreateSessionV0Request::ComputePath() const
{
	TMap<FString, FStringFormatArg> PathParams = { 
	{ TEXT("project_id"), ToStringFormatArg(ProjectId) } };

	FString Path = FString::Format(TEXT("/api/v0/projects/{project_id}/sessions"), PathParams);

	TArray<FString> QueryParams;
	QueryParams.Add(FString(TEXT("session_type=")) + ToUrlString(SessionType));
	Path += TCHAR('?');
	Path += FString::Join(QueryParams, TEXT("&"));

	return Path;
}

void OpenAPISessionManagerV0Api::CreateSessionV0Request::SetupHttpRequest(const FHttpRequestRef& HttpRequest) const
{
	static const TArray<FString> Consumes = { TEXT("application/json") };
	//static const TArray<FString> Produces = { TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("POST"));

	// Default to Json Body request
	if (Consumes.Num() == 0 || Consumes.Contains(TEXT("application/json")))
	{
		// Body parameters
		FString JsonBody;
		JsonWriter Writer = TJsonWriterFactory<>::Create(&JsonBody);

		WriteJsonValue(Writer, Body);
		Writer->Close();

		HttpRequest->SetHeader(TEXT("Content-Type"), TEXT("application/json; charset=utf-8"));
		HttpRequest->SetContentAsString(JsonBody);
	}
	else if (Consumes.Contains(TEXT("multipart/form-data")))
	{
		UE_LOG(LogIMSSessionManagerAPI, Error, TEXT("Body parameter (body) was ignored, not supported in multipart form"));
	}
	else if (Consumes.Contains(TEXT("application/x-www-form-urlencoded")))
	{
		UE_LOG(LogIMSSessionManagerAPI, Error, TEXT("Body parameter (body) was ignored, not supported in urlencoded requests"));
	}
	else
	{
		UE_LOG(LogIMSSessionManagerAPI, Error, TEXT("Request ContentType not supported (%s)"), *FString::Join(Consumes, TEXT(",")));
	}
}

void OpenAPISessionManagerV0Api::CreateSessionV0Response::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 200:
		SetResponseString(TEXT("A successful response."));
		break;
	case 400:
		SetResponseString(TEXT("Request contains invalid values. See error message for details."));
		break;
	case 401:
		SetResponseString(TEXT("Authentication credentials missing, invalid, or expired. See error message for details."));
		break;
	case 404:
		SetResponseString(TEXT("Returned when the resource does not exist or user does not have permission."));
		break;
	case 500:
		SetResponseString(TEXT("Internal server error. See error message for details."));
		break;
	case 0:
	default:
		SetResponseString(TEXT("An unexpected error response."));
		break;
	}
}

bool OpenAPISessionManagerV0Api::CreateSessionV0Response::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Content);
}

FString OpenAPISessionManagerV0Api::ListSessionsV0Request::ComputePath() const
{
	TMap<FString, FStringFormatArg> PathParams = { 
	{ TEXT("project_id"), ToStringFormatArg(ProjectId) } };

	FString Path = FString::Format(TEXT("/api/v0/projects/{project_id}/sessions"), PathParams);

	TArray<FString> QueryParams;
	QueryParams.Add(FString(TEXT("session_type=")) + ToUrlString(SessionType));
	Path += TCHAR('?');
	Path += FString::Join(QueryParams, TEXT("&"));

	return Path;
}

void OpenAPISessionManagerV0Api::ListSessionsV0Request::SetupHttpRequest(const FHttpRequestRef& HttpRequest) const
{
	static const TArray<FString> Consumes = {  };
	//static const TArray<FString> Produces = { TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("GET"));

	// Default to Json Body request
	if (Consumes.Num() == 0 || Consumes.Contains(TEXT("application/json")))
	{
		// Form parameters
		FString JsonBody;
		JsonWriter Writer = TJsonWriterFactory<>::Create(&JsonBody);
		Writer->WriteObjectStart();
		Writer->WriteObjectEnd();
		Writer->Close();
		HttpRequest->SetHeader(TEXT("Content-Type"), TEXT("application/json; charset=utf-8"));
		HttpRequest->SetContentAsString(JsonBody);
	}
	else if (Consumes.Contains(TEXT("multipart/form-data")))
	{
	}
	else if (Consumes.Contains(TEXT("application/x-www-form-urlencoded")))
	{
	}
	else
	{
		UE_LOG(LogIMSSessionManagerAPI, Error, TEXT("Request ContentType not supported (%s)"), *FString::Join(Consumes, TEXT(",")));
	}
}

void OpenAPISessionManagerV0Api::ListSessionsV0Response::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 200:
		SetResponseString(TEXT("A successful response."));
		break;
	case 400:
		SetResponseString(TEXT("Request contains invalid values. See error message for details."));
		break;
	case 401:
		SetResponseString(TEXT("Authentication credentials missing, invalid, or expired. See error message for details."));
		break;
	case 404:
		SetResponseString(TEXT("Returned when the resource does not exist or user does not have permission."));
		break;
	case 500:
		SetResponseString(TEXT("Internal server error. See error message for details."));
		break;
	case 0:
	default:
		SetResponseString(TEXT("An unexpected error response."));
		break;
	}
}

bool OpenAPISessionManagerV0Api::ListSessionsV0Response::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Content);
}

}
