/**
 * IMS Session Manager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIV0CreateSessionRequestBody.h"

#include "IMSSessionManagerAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace IMSSessionManagerAPI
{

void OpenAPIV0CreateSessionRequestBody::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (SessionConfig.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("session_config")); WriteJsonValue(Writer, SessionConfig.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIV0CreateSessionRequestBody::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("session_config"), SessionConfig);

	return ParseSuccess;
}

}
