/**
 * IMS Session Manager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPISessionManagerV0Api.h"

#include "OpenAPISessionManagerV0ApiOperations.h"
#include "IMSSessionManagerAPIModule.h"

#include "HttpModule.h"
#include "Serialization/JsonSerializer.h"

namespace IMSSessionManagerAPI
{

OpenAPISessionManagerV0Api::OpenAPISessionManagerV0Api()
: Url(TEXT("https://session-manager.ims.improbable.io"))
{
}

OpenAPISessionManagerV0Api::~OpenAPISessionManagerV0Api() {}

void OpenAPISessionManagerV0Api::SetURL(const FString& InUrl)
{
	Url = InUrl;
}

void OpenAPISessionManagerV0Api::AddHeaderParam(const FString& Key, const FString& Value)
{
	AdditionalHeaderParams.Add(Key, Value);
}

void OpenAPISessionManagerV0Api::ClearHeaderParams()
{
	AdditionalHeaderParams.Reset();
}

bool OpenAPISessionManagerV0Api::IsValid() const
{
	if (Url.IsEmpty())
	{
		UE_LOG(LogIMSSessionManagerAPI, Error, TEXT("OpenAPISessionManagerV0Api: Endpoint Url is not set, request cannot be performed"));
		return false;
	}

	return true;
}

void OpenAPISessionManagerV0Api::SetHttpRetryManager(FHttpRetrySystem::FManager& InRetryManager)
{
	if(RetryManager != &GetHttpRetryManager())
	{
		DefaultRetryManager.Reset();
		RetryManager = &InRetryManager;
	}
}

FHttpRetrySystem::FManager& OpenAPISessionManagerV0Api::GetHttpRetryManager()
{
	checkf(RetryManager, TEXT("OpenAPISessionManagerV0Api: RetryManager is null.  You may have meant to set it with SetHttpRetryManager first, or you may not be using a custom RetryManager at all."))
	return *RetryManager;
}

FHttpRequestRef OpenAPISessionManagerV0Api::CreateHttpRequest(const Request& Request) const
{
	if (!Request.GetRetryParams().IsSet())
	{
		return FHttpModule::Get().CreateRequest();
	}
	else
	{
		if (!RetryManager)
		{
			// Create default retry manager if none was specified
			DefaultRetryManager = MakeUnique<HttpRetryManager>(6, 60);
			RetryManager = DefaultRetryManager.Get();
		}

		const HttpRetryParams& Params = Request.GetRetryParams().GetValue();
		return RetryManager->CreateRequest(Params.RetryLimitCountOverride, Params.RetryTimeoutRelativeSecondsOverride, Params.RetryResponseCodes, Params.RetryVerbs, Params.RetryDomains);
	}
}

void OpenAPISessionManagerV0Api::HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const
{
	InOutResponse.SetHttpResponse(HttpResponse);
	InOutResponse.SetSuccessful(bSucceeded);

	if (bSucceeded && HttpResponse.IsValid())
	{
		InOutResponse.SetHttpResponseCode((EHttpResponseCodes::Type)HttpResponse->GetResponseCode());
		FString ContentType = HttpResponse->GetContentType();
		FString Content;

		if (ContentType.IsEmpty())
		{
			return; // Nothing to parse
		}
		else if (ContentType.StartsWith(TEXT("application/json")) || ContentType.StartsWith("text/json"))
		{
			Content = HttpResponse->GetContentAsString();

			TSharedPtr<FJsonValue> JsonValue;
			auto Reader = TJsonReaderFactory<>::Create(Content);

			if (FJsonSerializer::Deserialize(Reader, JsonValue) && JsonValue.IsValid())
			{
				if (InOutResponse.FromJson(JsonValue))
					return; // Successfully parsed
			}
		}
		else if(ContentType.StartsWith(TEXT("text/plain")))
		{
			Content = HttpResponse->GetContentAsString();
			InOutResponse.SetResponseString(Content);
			return; // Successfully parsed
		}

		// Report the parse error but do not mark the request as unsuccessful. Data could be partial or malformed, but the request succeeded.
		UE_LOG(LogIMSSessionManagerAPI, Error, TEXT("Failed to deserialize Http response content (type:%s):\n%s"), *ContentType , *Content);
		return;
	}

	// By default, assume we failed to establish connection
	InOutResponse.SetHttpResponseCode(EHttpResponseCodes::RequestTimeout);
}

FHttpRequestPtr OpenAPISessionManagerV0Api::CreateSessionV0(const CreateSessionV0Request& Request, const FCreateSessionV0Delegate& Delegate /*= FCreateSessionV0Delegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &OpenAPISessionManagerV0Api::OnCreateSessionV0Response, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void OpenAPISessionManagerV0Api::OnCreateSessionV0Response(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FCreateSessionV0Delegate Delegate) const
{
	CreateSessionV0Response Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr OpenAPISessionManagerV0Api::ListSessionsV0(const ListSessionsV0Request& Request, const FListSessionsV0Delegate& Delegate /*= FListSessionsV0Delegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &OpenAPISessionManagerV0Api::OnListSessionsV0Response, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void OpenAPISessionManagerV0Api::OnListSessionsV0Response(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FListSessionsV0Delegate Delegate) const
{
	ListSessionsV0Response Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

}
