/**
 * Payload Local API
 * The Payload Local API available in your running payloads. It provides an interface between your game server and the IMS zeuz orchestration service.  # Warning The Payload Local API is starting up at the same time as your game server, and may not be initially available. Use a retry mechanism to ensure the request is successful.  # OpenAPI Best practices The Payload local API is using the OpenAPI standard, it is advised to use an OpenAPI client generator for the language your game server uses. See a [list of OpenAPI client generators](https://openapi-generator.tech/docs/generators/).  # Address The Payload Local API address can be obtained using an environment variable: `http://${ORCHESTRATION_PAYLOAD_API}`.  # Authentication As the Payload Local API is only accessible from within the payload, it does not require authentication. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "CoreMinimal.h"
#include "OpenAPIBaseModel.h"

namespace IMSZeuzAPI
{

class IMSZEUZAPI_API OpenAPIPayloadLocalApi
{
public:
	OpenAPIPayloadLocalApi();
	~OpenAPIPayloadLocalApi();

	/* Sets the URL Endpoint.
	* Note: several fallback endpoints can be configured in request retry policies, see Request::SetShouldRetry */
	void SetURL(const FString& Url);

	/* Adds global header params to all requests */
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	/* Sets the retry manager to the user-defined retry manager. User must manage the lifetime of the retry manager.
	* If no retry manager is specified and a request needs retries, a default retry manager will be used.
	* See also: Request::SetShouldRetry */
	void SetHttpRetryManager(FHttpRetrySystem::FManager& RetryManager);
	FHttpRetrySystem::FManager& GetHttpRetryManager();

	class GetPayloadV0Request;
	class GetPayloadV0Response;
	class ReadyV0Request;
	class ReadyV0Response;
	class SetAnnotationV0Request;
	class SetAnnotationV0Response;
	class SetLabelV0Request;
	class SetLabelV0Response;
	
    DECLARE_DELEGATE_OneParam(FGetPayloadV0Delegate, const GetPayloadV0Response&);
    DECLARE_DELEGATE_OneParam(FReadyV0Delegate, const ReadyV0Response&);
    DECLARE_DELEGATE_OneParam(FSetAnnotationV0Delegate, const SetAnnotationV0Response&);
    DECLARE_DELEGATE_OneParam(FSetLabelV0Delegate, const SetLabelV0Response&);
    
    FHttpRequestPtr GetPayloadV0(const GetPayloadV0Request& Request, const FGetPayloadV0Delegate& Delegate = FGetPayloadV0Delegate()) const;
    FHttpRequestPtr ReadyV0(const ReadyV0Request& Request, const FReadyV0Delegate& Delegate = FReadyV0Delegate()) const;
    FHttpRequestPtr SetAnnotationV0(const SetAnnotationV0Request& Request, const FSetAnnotationV0Delegate& Delegate = FSetAnnotationV0Delegate()) const;
    FHttpRequestPtr SetLabelV0(const SetLabelV0Request& Request, const FSetLabelV0Delegate& Delegate = FSetLabelV0Delegate()) const;
    
private:
    void OnGetPayloadV0Response(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetPayloadV0Delegate Delegate) const;
    void OnReadyV0Response(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FReadyV0Delegate Delegate) const;
    void OnSetAnnotationV0Response(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSetAnnotationV0Delegate Delegate) const;
    void OnSetLabelV0Response(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSetLabelV0Delegate Delegate) const;
    
	FHttpRequestRef CreateHttpRequest(const Request& Request) const;
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
	mutable FHttpRetrySystem::FManager* RetryManager = nullptr;
	mutable TUniquePtr<HttpRetryManager> DefaultRetryManager;
};

}
