/**
 * Payload Local API
 * The Payload Local API available in your running payloads. It provides an interface between your game server and the IMS zeuz orchestration service.  # Warning The Payload Local API is starting up at the same time as your game server, and may not be initially available. Use a retry mechanism to ensure the request is successful.  # OpenAPI Best practices The Payload local API is using the OpenAPI standard, it is advised to use an OpenAPI client generator for the language your game server uses. See a [list of OpenAPI client generators](https://openapi-generator.tech/docs/generators/).  # Address The Payload Local API address can be obtained using an environment variable: `http://${ORCHESTRATION_PAYLOAD_API}`.  # Authentication As the Payload Local API is only accessible from within the payload, it does not require authentication. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIPayloadStatusPortV0.h"
#include "OpenAPIPayloadStatusStateV0.h"

namespace IMSZeuzAPI
{

/*
 * OpenAPIPayloadStatusV0
 *
 * Payload status.
 */
class IMSZEUZAPI_API OpenAPIPayloadStatusV0 : public Model
{
public:
    virtual ~OpenAPIPayloadStatusV0() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	OpenAPIPayloadStatusStateV0 State;
	/* Payload status details. */
	TOptional<FString> Details;
	/* Public IP address of the payload. */
	TOptional<FString> Address;
	/* External ports assigned to the payload. */
	TOptional<TArray<OpenAPIPayloadStatusPortV0>> Ports;
	/* last_reserved indicates the time this payload was last reserved. If the payload was reserved while it was already in a Reserved state, this timestamp is still updated. */
	TOptional<FDateTime> LastReserved;
	/* started indicates the time this payload started */
	TOptional<FDateTime> Started;
};

}
